interface("NSString");
interface("NSColor");
interface("NSObject");
interface("NSArray");
interface("NSMutableArray");
interface("NSDictionary");
interface("NSMutableDictionary");
interface("NSNumber");
interface("NSBundle");
interface("NSAlert");
NSAlertStyleWarning = 0;
interface("NSFileManager");
